workflows:
  moodle-android:
    name: Moodle Android Build
    max_build_duration: 120
    environment:
      android_signing:
        - dvdedukacija
      node: 24.16.0
      java: 17
    scripts:
      - name: Install dependencies
        script: |
          npm ci
          cd cordova-plugin-moodleapp && npm install && cd ..
      - name: Build and run Android
        script: |
          npm run prod:android -- --no-deploy
    artifacts:
      - platforms/android/app/build/outputs/bundle/release/*.aab
      - platforms/android/app/build/outputs/apk/release/*.apk
