workflows:
  moodle-android:
    name: Moodle Android Build
    max_build_duration: 90
    environment:
      android_signing:
        - dvdedukacija
      node: 24.16.0
      java: 17
    scripts:
      - name: Install dependencies
        script: npm ci
      - name: Build web
        script: npx ionic build --prod
      - name: Sync Android
        script: |
          npm run push -- --platform android
      - name: Build Android
        script: |
          cd android
          chmod +x gradlew
          ./gradlew
